apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  namespace: bookmyshow
  labels:
    app: bookmyshow
  annotations:
    # CRUCIAL: Tells GCP Load Balancer to talk to your Nginx pods via HTTP
    cloud.google.com/app-protocols: '{"http":"HTTP"}'
spec:
  type: LoadBalancer

  selector:
    app: bookmyshow

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
   
