apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookmyshow-monitor
  namespace: bookmyshow
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: bookmyshow
  endpoints:
    - port: metrics
      interval: 15s
